### ISSUE TITLE
Add more ESLint rules

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/starchart#102]
In https://github.com/Seneca-CDOT/starchart/pull/92#discussion_r1095838935 we've discussed some new ESLint rules we'd like to add/enforce with tooling:

1. Mandatory bracing - https://eslint.org/docs/latest/rules/curly
2. Use of proper logging over console.log - https://eslint.org/docs/latest/rules/no-console

**Comment by dadolhay** [comment]
I can take this, should be very quick

**Comment by humphd** [comment]
NOTE: #2 depends on the `logger` being added in #93.
