### ISSUE TITLE
Update seed.ts, for Record, Certificate, and Challenge tables

### ISSUE THREAD

**Issue by cychu42** [Seneca-CDOT/starchart#143]
We should add the ability to seed Record, Certificate, and Challenge tables, for future testing.

**Comment by humphd** [comment]
It would be great to make sure we 5 or so Records made of various types (A, CNAME, etc) with good examples so that @Myrfion, @Ririio, and @Eakam1007 working on front-end have things to use in their implementation.

**Comment by Ririio** [comment]
I have a question regarding the "ports" property. With the user being able to add as many ports as they want, should the value in the database be an array as to a string?
