### ISSUE TITLE
Setup initial Session

### ISSUE THREAD

**Issue by sfrunza13** [Seneca-CDOT/starchart#15]
Create a session file that will create a session for a hard coded user. This session can be created and retrieved from and set to requests headers as a cookie to be passed from route to route. This session will be created with actual user information coming from an IDP once we hook this up.

Using `createCookieSessionStorage` and methods like `getSession` and `commitSession` to retrieve the cookie from request header and `set-Cookie` to outgoing response respectively.

We can also check the session for expected keys such as `user-id` or whatever we choose as a field that will relate to the rest of our data.

Unlike with Telescope's Express Session Middleware these Session Storage objects such as Cookie Session Storage are handled on a route by route basis. This means that when you are writing a `loader` or `action` you take the Session info from the request header and then pass it along with `set-Cookie` on your response. On a file with a loader and an action you will likely end up doing each of these things twice.

**Comment by humphd** [comment]
@sfrunza13 is this done, and if not, can you clarify next steps?

**Comment by sfrunza13** [comment]
I realized most of this came with blues stack once I started making the login/logout buttons. To be clear none of session.server.ts is my work, but I think it's pretty good to use already.

**Comment by humphd** [comment]
So keep this open or close?  That's my main question.

**Comment by sfrunza13** [comment]
I can close it
