### ISSUE TITLE
Create a certificate table in the database

### ISSUE THREAD

**Issue by cychu42** [Seneca-CDOT/starchart#16]
We need to have a database table to store information about certificates we have created, for the project to utilize, such as showing users these information or know when a certificate would expire.
This can include: 
- Date of creation
- Expiration date
- Domain
- Retrieval link
- Owner
- Status of the certificate (E.g., expired)

**Comment by humphd** [comment]
What is "Retrieval link"?

**Comment by cychu42** [comment]
It's to show the users to let them download their SSL Certificates.

**Comment by cychu42** [comment]
Part of #59
