### ISSUE TITLE
UI Implementation for Login and Header

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/starchart#163]
I'll be working on implementing the UI for login and header based off the [figma](https://www.figma.com/file/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2109&t=ZfBYe62w5FXC70BW-1) template. I'll be working on combining all the routes for the domain and certificates based on the skeleton page provided from #138

**Comment by Eakam1007** [comment]
Hey, could you please explain what you mean by combining the routes? I am a bit confused

**Comment by humphd** [comment]
@Ririio you should be able to build the UI based on the skeleton routes @Eakam1007 just landed.

**Comment by Ririio** [comment]
> Hey, could you please explain what you mean by combining the routes? I am a bit confused

Oh I mean linking all the routes on the header component
