### ISSUE TITLE
Get experimental architecture working in docker-compose

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/starchart#2]
I'm hoping to mimic the setup we need via `docker-compose`, namely:

- a primary DNS server, where we define our zone(s)
- a secondary DNS server that forwards the zones in the primary
- a simple web server we can define an A record for and access by domain name

I've created and pushed an initial `docker-compose.yml` which creates all of the above, using two PowerDNS containers.  I've defined their `pdns.conf` files in `config/*`.

I need some help figuring out the various `pdnsutil` commands to run in order to properly setup the server(s) and to create a zone, for example: `starchart.com`.  I've assigned static IPs as follows:

- primary DNS server at `10.5.0.20`.  Nothing is exposed to the host
- secondary DNS server at `10.5.0.80`.  The API is exposed (i.e., `:8081`)
- web server at `10.5.0.100`. Nothing is exposed to the host

Running `docker-compose up` gets all of this running, but there is obviously more config to do.

I think a great test case would be:

1. define a zone, `starchart.com`, on the primary
2. set all the records to get everything setup correctly (this is where I'm stuck).  For example: NS, A, etc.
3. include a subdomain for the web server at `10.5.0.100` so you can hit `www.starchart.com` and get to nginx
4. get the primary to notify the secondary of the zone update, and have it sync there
5. use the secondary as our DNS to resolve `www.starchart.com` and get its default static page

**Comment by ctyler** [comment]
You'll need to expose UDP/53 from .10 and web (80/443) from .100 to the host to test this as you describe, assuming that you're testing from the host ("host" has lots of meaning here, I assume you're speaking of the system hosting the containers).

**Comment by ctyler** [comment]
You'll need to expose UDP/53 from .10 and web (TCP/80&443) from .100 to the host to test this as you describe, assuming that you're testing from the host ("host" has lots of meaning here, I assume you're speaking of the system hosting the containers).

**Comment by humphd** [comment]
That isn't really my issue.  See my PR at https://github.com/Seneca-CDOT/starchart/pull/3 for details.
