### ISSUE TITLE
Login / Sign Up - Implementation

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/starchart#22]
A sign up page that authenticates using Seneca email when creating an account.

- I suggest having the user be authenticated for their email instead of having them sign up directly using their Seneca account
- - Complication with Microsoft might occur in the future, and fixing issues can become complicated if it's external
- User display name (if required) can be taken (if possible) directly when the user authorizes the account creation through outlook

A login page that requires the user's email and password to access the web page.

- User should be allowed to have their login creds be saved or not
- Requires user's Seneca email and (custom password) to login to the site

**Comment by Eakam1007** [comment]
Does custom password means users will set up a new password for starchart specifically? 
I think we would be fine with SSO similar to telescope

**Comment by Ririio** [comment]
I guess we can still use an SSO, I just think that we should be able to sign in and out directly from the website without the need to redirect to Microsoft like we do in telescope.

**Comment by sfrunza13** [comment]
I believe it is decided that in the final production form of the auth flow we will be using Microsoft's Azure AD the way Telescope does. We should probably end up using an IDP to mimic a similar auth flow in dev as well but we could absolutely start with something like a smaller front-end component like a simple login form or just a button to begin with that will authenticate us as a hardcoded user to at least have something for the rest of the team to work from initially.
