### ISSUE TITLE
Add jest for unit testing

### ISSUE THREAD

**Issue by Eakam1007** [Seneca-CDOT/starchart#26]
Initial setup will be done based on Remix's Blues Stack (#7), which includes [Vitest](https://vitest.dev/) for unit testing. 
We would want to swap this out for [jest](https://jestjs.io/docs/using-matchers).

**Comment by humphd** [comment]
I've never used [Vitest](https://vitest.dev/) before, but given that it is compatible with Jest's `expect`, and also that it's already set up in our tree, and that it's actually already working (see @Genne23v's tests in #61), should we close this and use what we have?

**Comment by Eakam1007** [comment]
Yeah, I don't see any reason to replace it in that case
