### ISSUE TITLE
EsLint and Prettier Implementation

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/starchart#35]
As mentioned in the docs we should configure vscode settings to set up our prettier to allow for a smooth CI. 

``` Configure VSCode settings for prettier, eslint, extensions, etc. Build on [what we do in Telescope](https://github.com/Seneca-CDOT/telescope/tree/master/.vscode)Configure VSCode settings for prettier, eslint, extensions, etc. Build on [what we do in Telescope](https://github.com/Seneca-CDOT/telescope/tree/master/.vscode) ```

Both ESLint and Prettier should be implemented from the start to ensure that we minimize problems that may occur from conflicting coding style, and follow coding conventions.

**Comment by humphd** [comment]
It looks like the Blue Stack does a bunch of this config within the `package.json` file (there are already objects in there for config settings).  You can either use those, or rip them out and add separate config files if that's easier.

**Comment by Ririio** [comment]
I noticed that too, it seems a lot of configuration has already been done for me. I'll be focusing on adding rules and formatting for prettier, eslint and tsconfig
