### ISSUE TITLE
Documenting UI Templates

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/starchart#37]
To ensure that those who contribute on the creation of the UI of the website, must follow a template to prevent conflicting design.

- Contributors must document and compile all UI templates
- Template must be easy to read, and understand by non-front-end contributors
  - Is not final, and can be customized by all contributors

**Comment by Ririio** [comment]
We'll be using figma, and anyone who wants to participate can edit through this [linl](https://www.figma.com/file/88QbX1uesxfysuRPQNMv0l/Chakra-UI-Figma-Kit-(Community)?node-id=2102%3A2109&t=g5dTwpmysSz5GNPo-1)

**Comment by dadolhay** [comment]
Duplicate of #58
