### ISSUE TITLE
Fix Blue stack

### ISSUE THREAD

**Issue by sirinoks** [Seneca-CDOT/starchart#52]
The current blue stack configuration [can't be run](https://github.com/Seneca-CDOT/starchart/pull/40#issuecomment-1407488820). It is due to the bits of Blue Stack we need to rip out and fix. 

There seems to be a mismatch of a database solution and something about docker container problems, from what I've heard.

**Comment by humphd** [comment]
The Blue Stack issues relate to the Prisma database schema, data model, and session not matching, and TypeScript is unhappy that we're calling methods that don't exist.

We can either correct it, or rip out the code that's doing this, since we can add it back later in the correct way.
