### ISSUE TITLE
Prisma introduction in wiki

### ISSUE THREAD

**Issue by cychu42** [Seneca-CDOT/starchart#6]
Currently, there's no introduction for Prisma in our wiki to serve as a starting point to looking into the tool.
While the official site has [good documentation](https://www.prisma.io/docs/concepts/overview/what-is-prisma), we might  still want to add a helpful entry for navigating the this according to how we want to use it.

Some points to touch on:
- How to set it up
- How to connect to a MySQL database
- How to do CRUD operations

**Comment by sirinoks** [comment]
[Made a doc](https://github.com/Seneca-CDOT/starchart/wiki/Prisma)
Please see it, and let me know if there are any issues. If it's all good - close the issue. Or, perhaps, our current sheriffs should do that.

**Comment by sirinoks** [comment]
@cychu42 or, current sheriff @dadolhay 
The doc is ready. This is not really a PR, but I do think it needs to be reviewed. Please review yourself, or assign people to. When you see the doc being good enough, please close the issue.

**Comment by cychu42** [comment]
Great work! It's nicely organized.

I have a few thought, and please feel free to disagree with me.

1. I wonder if `To continue where we left off, proceed to the introspection step` should have a different wording, because it didn't occur to me at first that would go into how to pull database schema to `schema.prisma` file.

2. Maybe it's just me, "examples" sounds more like it's just more examples instead of new information. I feel query is important enough to have it's own section with how an entire query code would look like and what command to enter to run it, like [this page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/querying-the-database-typescript-postgres).

3. Similarly, I feel how one does migration can have its own mention outside of "example". You can point to [a page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres) that directly goes into explaining how one should setup models and run` npx prisma migrate dev`.

Also, as it is, you would want to highlight `prisma migrate dev` as code in "Typical Prisma workflows" section.

**Comment by sirinoks** [comment]
> 1. I wonder if To continue where we left off, proceed to the introspection step should have a different wording, because it didn't occur to me at first that would go into how to pull database schema to schema.prisma file.

Could you please explain more what you mean?

> 2. Maybe it's just me, "examples" sounds more like it's just more examples instead of new information. I feel query is important enough to have it's own section with how an entire query code would look like and what command to enter to run it, like [this page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/querying-the-database-typescript-postgres).

Sure. So, instead of the example, I better add a more concrete guide on how to query the database. 

> 3. Similarly, I feel how one does migration can have its own mention outside of "example". You can point to [a page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres) that directly goes into explaining how one should setup models and run npx prisma migrate dev.

Do you think I should also replace it with concrete steps, or just add a link next to what I already have there?

> Also, as it is, you would want to highlight prisma migrate dev as code in "Typical Prisma workflows" section.
Yes, agreed, missed this.

To add to this, I saw you were dealing with Prisma already in our project. Anything you would like to add due to your direct experience?

**Comment by sirinoks** [comment]
@sirinoks TODO: 2.

**Comment by cychu42** [comment]
> Could you please explain more what you mean?

It can just be me being unfamiliar with the term `introspection`. I tried to look up the term, and it didn't occur to me it would involve pulling the schema. It makes more sense once I read [this page](https://www.prisma.io/docs/concepts/components/introspection) on Prisma website about introspection.

> Do you think I should also replace it with concrete steps, or just add a link next to what I already have there?
I would say either show concrete steps or link a page that goes directly into the steps. I feel asking people to go through guides to find a basic use can create barrier to the information. Not that people should never read, but migration would be very useful to highlight.

> To add to this, I saw you were dealing with Prisma already in our project. Anything you would like to add due to your direct experience?

That's about it. When I wrote the comment, I thought about what I would appreciate when I was reading about Prisma.

**Comment by sirinoks** [comment]
@cychu42 [Updated the doc](https://github.com/Seneca-CDOT/starchart/wiki/Prisma).
- Added a step of querying the database, reworded "next steps" if a user wants to check out official guides.
- Changed some confusing titles, like "examples" changed into "set up".
- Added a link to migration doc. I don't exactly want to change what I have there in that section, I have added a link to the full process, but in this doc I just want the user to have some idea of it, that it exists, how it looks like, and, of course, a definition of a migration itself. Because when I was looking at the official docs - that was the question I had - `what even is migration..?`.

**Comment by cychu42** [comment]
@sirinoks Looks great! I notice just one thing that needs to be added. There are steps missing before one can use `npx ts-node index.ts` for query:
1.  `npx prisma db pull` to pull the schema to `schema.prisma`
2. `npm install @prisma/client` to install Prisma client
3. `npx prisma generate` to generate the client base on the pulled schema in `schema.prisma`
4. run `npm install typescript ts-node @types/node  --save-dev` to install  typescript, ts-node, and @types/node

**Comment by sirinoks** [comment]
@cychu42 Just so I get it right, should this go after step 2, or before it?
Currently I'm planning to insert it after 2, before 3.

**Comment by cychu42** [comment]
Anywhere between end of step 2 to start of step 3 would work.

**Comment by sirinoks** [comment]
Great, done

**Comment by cychu42** [comment]
I think you should put in at start of step 3 instead, since you say `Now that you have generated Prisma Client` in the beginning, so that makes more sense.
Also `npx prisma db pull` is missing `pull`, and  `npm install typescript ts-node @types/node  --save-dev` has the extra `run`.

**Comment by cychu42** [comment]
Alternatively, you can get rid of `Now that you have generated Prisma Client` bit instead of moving the added steps.

**Comment by sirinoks** [comment]
> Also npx prisma db pull is missing pull, and npm install typescript ts-node @types/node  --save-dev has the extra run.

Thanks, I'm sleepy, missed those

**Comment by cychu42** [comment]
What you have now is fine, but you probably want to delete `Now that you have generated Prisma Client` now, since the instruction goes into installing and generating the client after it.

**Comment by cychu42** [comment]
Oh, there is an extra N in `NYou'.

**Comment by cychu42** [comment]
LGTM!
