### ISSUE TITLE
Cancel other jobs if one fails during CI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/starchart#65]
While reviewing https://github.com/Seneca-CDOT/starchart/pull/64, I notice that the Blue Stack CI is adding logic to cancel parallel jobs if one of the jobs fails.  This is nice so you don't burn through build minutes if you know the whole thing is going to fail.

I looked at how they do it using https://github.com/styfle/cancel-workflow-action, and it recommends to use the built in logic in GitHub Actions, see:

https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

cc @SerpentBytes, @shawnyu5.

**Comment by shawnyu5** [comment]
If we move starchart into a separate repo, we will still get billed for action minutes? (I dont know how gh org billing works, and the docs are kinda confusing).

Let me look into this, I wonder if there are side effects of canceling a job mid-way through. ie in the middle of installing dependencies, and how caching will handle this.
