### ISSUE TITLE
ci: `Run andymckay/cancel-action@0.2 6 Error: Resource not accessible by integration"`

### ISSUE THREAD

**Issue by shawnyu5** [Seneca-CDOT/starchart#99]
A discussion that started on slack, moving to here.

Since we wanted parallel jobs, Github actions do not natively support canceling parallel jobs. So the action, that cancels parallel jobs, calls out to the GitHub api to do it. 

Also the built-in [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) key seems to do something different than what we want it to do... That is mainly for making sure there is a single instance of CI running at a time. To make sure there is one action deploying the application for example.

---

Did some research on this, seems like not all forks have enough permission to access the gh api of the star chart repo

Read up on 2 issues:

https://github.com/actions/first-interaction/issues/10
https://github.com/actions/labeler/issues/12

There doesn't seem to be a workaround for this. Either we give up on canceling parallel jobs, or we go back to jobs being sequential, allowing each action to depend on the previous one passing before starting.

**Comment by shawnyu5** [comment]
Sounds good

**Comment by humphd** [comment]
You can probably make a branch and do: `git revert fb2cfe38e2cd2005a396b8495803ace8e060525a` to have it automatically undo this for you.
